### ISSUE TITLE
UI: Task Arguments screen ambivalent 

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#1095]
This task launch screen would suggest that task arguments shall be submitted like the following:

dataflow-server-username=marlene
dataflow-server-password=supersecret

![image](https://user-images.githubusercontent.com/685363/53558935-24c41080-3aed-11e9-9e57-ca2a1eb5c8a3.png)

That does not seem to work. Interestingly this one worked:

![image](https://user-images.githubusercontent.com/685363/53559119-83898a00-3aed-11e9-9be5-552fbeea287e.png)

**Comment by oodamien** [comment]
![image](https://user-images.githubusercontent.com/487067/53572632-fc2f2b80-3b6b-11e9-87d5-e37d0418e5fe.png)

will performed the following rest call:

![image](https://user-images.githubusercontent.com/487067/53572661-0b15de00-3b6c-11e9-916b-432234a400ce.png)

**Comment by sabbyanandan** [comment]
The arguments to Tasks are always expected to be passed with `--` prefix. That's how it is done in the Shell as well. It used to be the same experience in the previous UI screens. 

I don't think we would want to change it to automate in the UI because then it'd be confusing to users when switching between the UI and Shell. Let's try to keep it consistent and not change the behavior in v2.0.
