### ISSUE TITLE
"Details" button in "Apps" tab of dashboard is kind of underwhelming

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#127]
_From @dsyer on October 3, 2016 12:15_

There's no description of the app, only a list of properties (which could be useful I know). I'd expect at least a sentence if not a complete README. Maybe a link to the app source code in github? It's also really slow.

N.B. The property names are capitalized by the browser which is probably not helpful.

_Copied from original issue: spring-cloud/spring-cloud-dataflow#918_

**Comment by BoykoAlex** [comment]
@sabbyanandan @aclement The description is missing because the request response never has the app description - the property `shortDescription` is `null` in the JSON response. The operation is slow because it takes ~2-3s for the request to be answered. I can only see us making the property name not to start from upper case character and perhaps make it a separate page instead of the dialog might be good to address issues @ghillert raised previously about truncation/overlapping...

**Comment by dsyer** [comment]
I don't see how we can be closing this issue when nothing happened. If the description in the JSON is null isn't that a content problem?

**Comment by BoykoAlex** [comment]
@dsyer The issue is not closed but rather moved on the backend https://github.com/spring-cloud/spring-cloud-dataflow/issues/918.

**Comment by sabbyanandan** [comment]
@dsyer: Sorry for the confusion. This will be addressed in the backend via: spring-cloud/spring-cloud-dataflow#918.
