### ISSUE TITLE
Update to Angular 9

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1338]
Highlights:
- A new rendering engine is in the works
- The minified version shrinks by 10-20% in size
- .. 

Whenever it is released, let's try it out to make sure our tests run successfully, and likewise, the feature-set continues to work as expected.

**Comment by sabbyanandan** [comment]
Requires https://github.com/spring-projects/spring-flo/issues/64

**Comment by BoykoAlex** [comment]
@oodamien I have created two branches for Flo angular 9 adoption.
1. *angular9* - switch dependencies to angular 9 but old compilation
2. *angular9-plus* - includes ivy compilation of Flo lib and some rework to for the sample app to get rid of prehistoric `systemjs` and building with `ng-packagr` rather than manually with `ngc` and then `rollup`.
Please give them a try :-)
