### ISSUE TITLE
Palette renders poorly on Brave

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1374]
I see this on the latest from `master` (2.4 BS image) on Minikube.

![image](https://user-images.githubusercontent.com/1562654/73375880-5ac7c280-4271-11ea-96d6-ff4dc5506bcf.png)

**Comment by BoykoAlex** [comment]
@sabbyanandan I'd like to take a look at this but would need steps to reproduce this issue... Looks like it is not reproducible with local server...

**Comment by sabbyanandan** [comment]
Hmm, I also see things rendering just fine on the "latest" Docker Compose experience. What I tried earlier today was the latest SCDF-image running in K8s (through Minikube).

1) Start K8s cluster in Minikube
2) Run the following deployments from SCDF root directory
```
kubectl create -f src/kubernetes/rabbitmq/
kubectl create -f src/kubernetes/mysql/

kubectl create -f src/kubernetes/skipper/skipper-config-rabbit.yaml
kubectl create -f src/kubernetes/skipper/skipper-svc.yaml
kubectl create -f src/kubernetes/skipper/skipper-deployment.yaml

kubectl create -f src/kubernetes/server/server-roles.yaml
kubectl create -f src/kubernetes/server/server-rolebinding.yaml
kubectl create -f src/kubernetes/server/service-account.yaml
kubectl create -f src/kubernetes/server/server-config.yaml
kubectl create -f src/kubernetes/server/server-svc.yaml
kubectl create -f src/kubernetes/server/server-deployment.yaml
```
3) Once when SCDF is up and running, open Dashboard, and register Docker apps
3) Go to "Create Streams"

**Comment by BoykoAlex** [comment]
I'm unable to reproduce this issue... Maybe some glitch building dom nodes in the browser was the culprit... The screenshot implies that size of the text node was empty although under normal circumstances at this moment the size should be non-empty (should be the size of the text label). Not sure what led to the empty size.
@sabbyanandan Did you see this once only? If you can't reproduce this reliably either I propose to keep an eye out for this... ping me next time you get it...

**Comment by BoykoAlex** [comment]
I have tried SCDF UI local build with Brave browser
Tried deploying on docker-desktop k8s cluster - worked fine with Brave browser
Couldn't try minikube... cannot get my-sql service to in my minikube cluster, some issue with persistent volume claim... However, i think docker-desktop working is really the same thing
I confirm the issue on Sabby's K8s instance. Unfortunately, i cannot debug it at all because source maps are missing on the production build.
@sabby I propose you to include source maps into the SCDF UI and then deploy SCDF on K8s. Thus I should be able to open SCDF UI served from your K8s instance and debug the code in the browser.
Instructions:
1. Locate 'pom.xml' in SCDF UI and set the maven artifact version to `2.4.1.BUILD-SNAPSHOT`. Save the file. (i.e. `<version>2.4.1.BUILD-SNAPSHOT</version>` at the top of the file)
2. Locate `ui/package.json` file in SCDF UI. Find the line with (line 18 for me):
```
    "mavenbuild-without-tests": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --output-path ./../target/classes/public/dashboard --base-href /dashboard/",
```
and add this parameters: `--source-map`
Such that the line becomes:
```
    "mavenbuild-without-tests": "node --max_old_space_size=4096 ./node_modules/@angular/cli/bin/ng build --prod --source-map --output-path ./../target/classes/public/dashboard --base-href /dashboard/",
```
3. Run SCDF UI build with `install` rather than package: `./mvnw clean install -DskipTests` (SCDF UI is installed into local m2 repo). Note the maven artifact version of SCDF UI.
4. Locate `pom.xml` in SCDF source code. Change SCDF UI version in that file to `2.4.1.BUILD-SNAPSHOT`. (i.e. `<spring-cloud-dataflow-ui.version>2.4.1.BUILD-SNAPSHOT</spring-cloud-dataflow-ui.version>` it is line 58 for me)
5. Run SCDF build: `./mvnw clean install -DskipTests`
6. Deploy to desired k8s cluster with Sabby's instructions two comments above

**Comment by BoykoAlex** [comment]
@sabbyanandan @oodamien might be some settings in the Brave browser causing this to happen. Truncation utility builds DOM elements off the screen to check text size etc... Perhaps for something served not locally Brave browser prevents building DOM elements off the page.

**Comment by sabbyanandan** [comment]
On the latest 2.5 BS build, I do not see the rendering issues on Brave anymore. See:

![image](https://user-images.githubusercontent.com/1562654/74977912-7b9eb600-53e0-11ea-9d98-f4950fe92645.png)

**Comment by sabbyanandan** [comment]
Unfortunately, this is still a problem in the Dockerized provisioning of SCDF on K8s. What I shared previously was from CF, and that was a miss.
