### ISSUE TITLE
Bulk register widget shouldn't include hardcoded bit.ly links

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#146]
As a developer, I'd like to replace the hardcoded bit.ly links with a dynamic approach, so we don't require a new release of UI/SCDF for every new release of app-starters. 

**Acceptance:**
- dynamic resolution of bit.ly links needs to be considered in the design
- deriving the version from `dataflow-server.yml` could be an option

Depends on https://github.com/spring-cloud/spring-cloud-dataflow/pull/1140

**Comment by xtreme-sina** [comment]
The bit.ly URI's are misleading CF users to think docker is supported (and k8, mesos users that uber-jars are supported). If it’s in the UI then it is supported. The UI should pull the links that are only relevant to the corresponding server. Ideally dynamically.

Note I don't think this applies to bindings because a single server could support multiple bindings.

**Comment by sabbyanandan** [comment]
Thanks for the feedback, @xtreme-sina. We are removing the bulk registration capability via [spring-cloud/spring-cloud-dataflow-ui#165](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/165). 

We will be adding "app-marketplace" like capability in the app-starters project's site, so it will be simple as copying the maven/docker coordinates and register them as needed.
