### ISSUE TITLE
Improve placeholder of task launching "Arguments" textfield

### ISSUE THREAD

**Issue by benas** [spring-cloud/spring-cloud-dataflow-ui#1537]
When launching Spring Batch jobs that are wrapped in SC tasks, job parameters are passed in key/value pairs like `name=foo` without the `--`. However, the placeholder of the "Arguments" textfield shows only the `--myarg=myvalue` syntax:

![Screenshot 2020-08-18 at 16 51 42](https://user-images.githubusercontent.com/1210553/90548668-971b2b80-e18d-11ea-856b-bb27624d1467.png)

This could be confusing to users who might:

* pass job parameters using the `--param=value` syntax which is incorrect
* try to pass the job parameters in the "Properties" text field (See referenced SO question) which is incorrect as well

Even though the tooltip icon mentions that arguments can be prefixed with `--` which is optional, I think we can make the text more explicit about how to pass arguments and Spring Batch job parameters. This does not seem to be documented neither in here:

* https://dataflow.spring.io/docs/batch-developer-guides/batch/data-flow-spring-batch/#launching-the-task
* https://dataflow.spring.io/docs/feature-guides/batch/deployment-properties/#how-to-set-these-properties

Wdyt?

-----

SCDF version: 2.6.0
Reference: https://stackoverflow.com/questions/63420316/providing-job-parameter-via-spring-cloud-data-flow-ui

**Comment by sabbyanandan** [comment]
Hi, @benas. We have a larger goal to completely redesign the Task launch page and to make it more interactive as it is for the stream deployments. That effort is tracked through this epic: https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/1514. 

![image](https://user-images.githubusercontent.com/1562654/93615218-f4222100-f987-11ea-82b1-b6fefbaf7a56.png)

I will close this as a duplicate since this page would look differently, and definitely, the params/args would have a different UX, as well.
