### ISSUE TITLE
Task complete status incorrectly reported

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#1726]
Step1: Launch to fail a task intentionally (I launched `timestamp-batch` with a NO new arg, so it can fail):

> Notice that the exit code is "1", but the status shows as `COMPLETE`.
> I should see `ERROR` instead.

![image](https://user-images.githubusercontent.com/1562654/119708764-52ee4300-be11-11eb-9886-11eb89f90f0e.png)

Step2: Relaunch the task successfully (add a unique arg in my case):

> Notice that the exit code is "0", but the status shows as `ERROR`.
> I should see `COMPLETE` instead.

![image](https://user-images.githubusercontent.com/1562654/119709190-cbed9a80-be11-11eb-9742-d4b31e554fef.png)

**Comment by cppwfs** [comment]
Not able to reproduce this issue on 2.8.X-SNAPSHOT running on kubernetes (minikube).
Launch Task Batch first time:
![image](https://user-images.githubusercontent.com/695673/119719135-6b248900-be36-11eb-99be-15125a8ca1c6.png)
Relaunch to fail
![image](https://user-images.githubusercontent.com/695673/119719224-87282a80-be36-11eb-9ee8-7813f8e9c424.png)
Relaunch setting commandline arg to foo=bar
![image](https://user-images.githubusercontent.com/695673/119719382-b6d73280-be36-11eb-9b70-9e96397baf44.png)

**Comment by jvalkeal** [comment]
I don't see this happening anywhere either.

**Comment by jvalkeal** [comment]
I wonder if these are somewhat related to task execution cleanup.

**Comment by oodamien** [comment]
It's not an UI issue since the status is populated by the API data.

**Comment by jvalkeal** [comment]
I just realised a same thing as that task in execution page just reflects "task" status.

**Comment by cppwfs** [comment]
The resolution to this issue is to remove the status field from the task execution detail page.   Because this is the status for the task definition (meaning the status of the last execution).   And we are looking at a specific task execution, which may not be the last execution.   
To reproduce:
1) Launch timstamp-batch.  Let 's say it creates task execution 1.
2) Relaunch timestamp-batch.   Let's say it creates task execution 2.

Look at task execution 2 and it will show `error` for the status.
Look at task execution 1 and it will also show `error` for the status.
This because that section of the report shows information for the task definition.    So the status for the task definition is correct, but for this page it is misleading.

**Comment by cppwfs** [comment]
Instead of removing it we could update the label for the status to  "Last Execution Status".   This may help with the confusion.
