### ISSUE TITLE
Translation issue in modal dialog of cleaning up task executions (modal body)

### ISSUE THREAD

**Issue by klopfdreh** [spring-cloud/spring-cloud-dataflow-ui#1881]
There is an issue when you clean up all task executions. As you can see here:

https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/main/ui/src/app/manage/tools/cleanup/cleanup.component.html#L10

and here

https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/main/ui/src/assets/i18n/en.json#L343

the property `tools.modal.cleanUp.removing` is missing - my assumption is that this could be translated with

EN: `Removing all entries.`
DE: `Entferne alle Einträge.`

**Comment by klopfdreh** [comment]
Maybe `tools.modal.cleanUp.processing` was meant but referenced in a wrong way. Anyway the provided translations in the description of the tickets fits better than `Removing data`.

**Comment by claudiahub** [comment]
Thanks @klopfdreh for pointing this out and providing a proper german translation 😄 
I have also cleaned up `tools.modal.cleanUp.processing` since this is not used anymore on our side.
Also I've provided a little more meaningful name for the string `tools.modal.cleanUp.removingAll` so if in the future we'll need to have another label for removing just one entry we could just add `tools.modal.cleanUp.removing`.
