### ISSUE TITLE
The wild card '*' status is stored as * on transitions

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#197]
When using the designer the '*' is stored as a * without the quotes.

**Comment by aclement** [comment]
There is a distinction here that '*' means any exit status whilst * means any exit code.  I knew about this issue but from the sample docs and examples I'd seen it didn't seem they were making this distinction and were allowing the use of either to mean 'everything else' (and I bet in many situations * and '*' do mean basically the same thing).

We made a late change to allow the quotes to be added automatically by the graph->dsl code so that the user wasn't having to worry about them in the designer. But there were some subtleties around * that were ignored in the quest for MVP.

Does this current behaviour break you Glenn?

**Comment by cppwfs** [comment]
At this point CTR doesn't handle the * alone.  It requires it to be in quotes.  In the next release we will be handling exit codes.

**Comment by aclement** [comment]
The workaround right now is for a wildcard exit status transition, explicitly quote it when specifying it in the UI and it will remain quoted in the DSL. We only 'auto-quote' things that aren't numbers or wildcard (so specifying a number will pass through and be considered an exit code).

I'm just debating whipping up a quick PR to quote everything, including numbers and wildcards, seeing as composed-task-runner can handle anything unquoted right now.  Worth it?

**Comment by cppwfs** [comment]
Don't worry about it, my bad.  I'm getting punchy.

**Comment by aclement** [comment]
No, you are onto something. I've just been testing around it and there is an inconsistency it would be nice to sort out.
