### ISSUE TITLE
Unable to access "/about" page with basic security enabled

### ISSUE THREAD

**Issue by trisberg** [spring-cloud/spring-cloud-dataflow-ui#199]
If I try to access http://localhost:9393/about with basic security enabled I get redirected to the login form and then to the apps page. Trying the http://localhost:9393/about url again in the browser I get redirected to the login form again with a message "PLEASE SIGN OUT FIRST". Haven't found a way to access the `/about` page so far.

Using curl like this works fine: `curl -u user:secret9 http://localhost:9393/about`

**Comment by ghillert** [comment]
This behavior is by design. You typically have to send the `application/json` accept header to hit the REST endpoints. That will trigger the Basic Auth credentials being asked for. Otherwise, the browser thinks that you want to access the Dashboard UI.

The UI in return does not use basic authentication but uses an `xauth` header which is basically the Session Id.

@sabbyanandan  Maybe as an `2.0` epic, it would be preferable to have the Rest API under `/api` and have the UI (Dashboard) reside under the root `/`. That would have simplified the setup a bit.

Just to explain the flow:

1. You browse to the UI and login
2. If you then go to `/about` the server does not know that it is you (no xauth-header submitted)
3. It redirects you to the login page
4. The xauth-token is stored in local-storage and is dehydrated/restored
5. That’s why you see the `please sign out first` message
