### ISSUE TITLE
Counter rates oscillate between 0 and some value  

### ISSUE THREAD

**Issue by markpollack** [spring-cloud/spring-cloud-dataflow-ui#213]
The polling to display counter rates will oscillate between 0 and some value even though the incoming message rate is stable.

![counter-rates](https://cloud.githubusercontent.com/assets/247466/25853703/b7f15458-349b-11e7-801c-cee161a6f7cb.png)

**Comment by ilayaperumalg** [comment]
I believe this is the expected behaviour and works as `designed`. May be we can add a better strategy to handle the `zero` messages/second.

Currently, we have been using [logic](https://github.com/spring-cloud/spring-cloud-dataflow-ui/blob/master/ui/app/scripts/analytics/controllers/metric.js#L38) to calculate the rate based on the previous total messages and the current count with respect to the `refresh` time interval.

In most cases, the `refresh` time interval `1` works better but it could also bring `zero` when the retrieved count is equal to the previously retrieved one (depends on the time the trigger gets the count from redis within that second period).

**Comment by sabbyanandan** [comment]
Analytics tab is removed in v2.0. This is not relevant anymore.
