### ISSUE TITLE
Filtering in stream-list-view does not alter the results on keypress

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#305]
As a user, I'm filtering the stream list by searching for a particular string, but the results remain unaltered. I'm expected to hit the search button manually and it is not consistent with what's offered in the Apps tab.

**Comment by cppwfs** [comment]
This worked for me.  Can you clear your cache and retry?

**Comment by jvalkeal** [comment]
There is no automatic filtering in stream list page as it is based on server side filtering while apps list page is based on client side filtering. User needs to click that search button.

This is a reason why apps list page is effectively broken where filtering gives wrong pagination controls because if server side pagination is in use, filtering and sorting needs to happen on a server side.

We really can't do automatic re-search based on key events from search input field as that would then cause cascading http request with every key press. We need to create a better model for how data is updated from server side and for apps list we need to implement server side filtering per https://github.com/spring-cloud/spring-cloud-dataflow/issues/1617.

ngrx is a way to go as it makes these things simpler to handle. In old UI we continuously updated page in every 5 secs and search filter was added to next request.

**Comment by sabbyanandan** [comment]
Thanks, @jvalkeal.
