### ISSUE TITLE
Polish and clean some flo files

### ISSUE THREAD

**Issue by jvalkeal** [spring-cloud/spring-cloud-dataflow-ui#390]
Some quick polish happened with flo PR #388 merge. Some files like `render.service.ts` and `text-to-graph.ts` needs some heavy polishing as looks like some commented code might be needed for WIP.

- [x] `render.service.ts`
- [x] `text-to-graph.ts`

**Comment by aclement** [comment]
text-to-graph - has had a good pass over it and an improved test suite written. It is not quite complete though because it tests converting text to a JSON graph but the code in text-to-graph has been tidied/polished I believe.

graph-to-text - has been through a complete rewrite, fully tested now and fully polished.

**Comment by sabbyanandan** [comment]
This has been addressed in the recent comments from @BoykoAlex and @aclement. We will continue to improve on this front in the next milestone. I will move it to 1.3 M3 to keep track of it.

**Comment by sabbyanandan** [comment]
@BoykoAlex: Perhaps the remaining portion of this is addressed in https://github.com/spring-cloud/spring-cloud-dataflow-ui/commit/3ffd2cfd7588c86bb3835015e5a9b4ee3c211cec?

**Comment by BoykoAlex** [comment]
I'd close it for now.
