### ISSUE TITLE
Add suite of E2E tests 

### ISSUE THREAD

**Issue by ghillert** [spring-cloud/spring-cloud-dataflow-ui#456]
We should add a basic set of E2E tests. Initially we should migrate as many of the old UI's E2E tests as possible.

**Comment by ghillert** [comment]
Build upon what we have - Angular CLI does use the same method using Protractor as the old UI - Therefore some E2E test may even migrate easily - See also: https://github.com/angular/angular-cli/wiki/e2e

**Comment by cppwfs** [comment]
Breaking this story into components so that the work can be distributed.  The new stories are:
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/544
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/545
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/546
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/547
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/548
https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/541
