### ISSUE TITLE
Delay in mouse focus on DSL-editor

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#475]
Navigating to a specific position in DSL-editor appears to have a slight delay in rendering. (click the gif below to see it in action)

![delay_in_rendering](https://user-images.githubusercontent.com/1562654/30495072-6023c12e-99ff-11e7-95fb-ab86e9aa863e.gif)

**Comment by ghillert** [comment]
Confirmed on my machine as well and also reported by @viniciusccarvalho. The issue is more pronounce on Chrome. You still see a lag in Safari but it is MUCH less pronounced.

The issue, though is much larger than that. It is a major issue while editing properties for components.

It looks like (feeling), relating to data-binding issues.

**Comment by ghillert** [comment]
@sabbyanandan @BoykoAlex Also created https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/518

**Comment by sabbyanandan** [comment]
This is not happening anymore.
