### ISSUE TITLE
Port sync-node functionality

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#496]

**Comment by sabbyanandan** [comment]
@BoykoAlex: We will attempt to address this based on your understanding - please share your thoughts.

**Comment by BoykoAlex** [comment]
@jvalkeal was that for the `exitCode` property? If yes then `exitCode` is a property on a link (transition) that is once set results visually in a label on a link and link becoming dashed instead of solid. Once `exitCode` is back to blank (`undefined`) then the link should visually be back to normal: no label, solid line style
