### ISSUE TITLE
Task Launch can't add a command line argument that does not have a value

### ISSUE THREAD

**Issue by cppwfs** [spring-cloud/spring-cloud-dataflow-ui#555]
From the UI I can't add a command line argument that does not have a value. i.e. --debug

**Comment by sabbyanandan** [comment]
Can we do `--debug=true` - will that be enough?

**Comment by cppwfs** [comment]
--debug is an example.  In its case -debug=true will work.  I was thinking more of when folks just add a single flag to their app.

**Comment by sabbyanandan** [comment]
The general perception is that for any "flag", there has to be a default behavior (either true or false). The UI takes the opinionated approach to supply the value for flags more explicitly (that's why 2-text-boxes). 

I'll mark it as invalid. If we have a more concrete use-case requirement, we can revisit then.
