### ISSUE TITLE
Revisit application-specific property validation

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#557]

**Comment by BoykoAlex** [comment]
@aclement @sabbyanandan I recall us creating this and I do recall having a very vivid picture of what needs to be done but I ashamed to tell you that I forgot what exactly we wanted to do here... Would you be able to remind me?

**Comment by aclement** [comment]
I think we changed our mind in a recent call.  The problem is that there are properties you can specify that are not listed in the metadata but are still valid. Currently if you use them you have to use the shell to define the stream because you can't press the button in the UI. The simplest simplest change is to allow them to press create if all they have is property validation errors. (the bigger alternative we moved away from was a widget on the UI for turning that validation on/off)

**Comment by BoykoAlex** [comment]
Ah, yes!-) Thank you! If it's a limited set of such properties we could just hard code them in the meta-model similarly to properties for `destination` and `tap` as well as `label` and `stream-name` properties. If those properties not defined in the metamodel are dynamic then we'd need to ignore property validation errors.
If it's only properties to gather metrics on modules such as: `spring.cloud.stream.bindings.applicationMetrics.destination=metrics` or whatever it has evolved to then we may just add in our metamodel and be done with it?

**Comment by sabbyanandan** [comment]
Andy's explanation covers it all. The fact that we have the metadata-file as an optional artifact for each application, it is possible that we may not have all the relevant properties (in Flo) to validate it completely. We make the best attempt to validate for acceptable properties; if it isn't available, we can simply enable the create-button, so it will be consistent with how the Shell accepts it.

**Comment by sabbyanandan** [comment]
Closing this since there aren't any other scope for improvements to Flo itself.
