### ISSUE TITLE
Unable to access to root endpoint when security is enabled

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#560]
As a user, I'm trying to gain access to the root URI, so I can review the list of available endpoints. However, when the security is enabled, I'm unable to get to it. I'm prompted with "Please sign out first" message instead.

I tried the following roles.

1)
![image](https://user-images.githubusercontent.com/1562654/33325074-290152a6-d406-11e7-85b4-3ab3a647f6f4.png)

2) 
![image](https://user-images.githubusercontent.com/1562654/33325206-7cf4a1ce-d406-11e7-801c-6be5a9019f15.png)

**Comment by ghillert** [comment]
Created ticket for the redirect to the login-page UX issue https://github.com/spring-cloud/spring-cloud-dataflow/issues/1818

**Comment by ghillert** [comment]
Created https://github.com/spring-cloud/spring-cloud-dataflow/issues/1820

**Comment by ghillert** [comment]
This issue is unfortunately by design. The issue is that when you access the root, you operate outside of the application (to the server you are basically not authenticated). Therefore, because you don’t provide a JSON header (I believe we look at the Browser string itself), we think you are a browser and redirect you to the login page.

There however, we get the xauth token from local storage, and use it to ping the server - therefore the message that you are still logged in. The redirect to the login page is not the best UX - I created spring-cloud/spring-cloud-dataflow#1818 as a fix for that.

Otherwise, we can probably close this issue.

**Comment by sabbyanandan** [comment]
Thanks! And yes, once we move the endpoints under `/api` (for 2.0), we will have a cleaner approach to all this.
