### ISSUE TITLE
Cleanup Task "Apps" tab

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#62]
As a developer, I'd like to change the "coordinates" column with "description" of the task application.

![image](https://cloud.githubusercontent.com/assets/1562654/15714926/6a3d770a-27d1-11e6-84d9-4b39b43b5ecb.png)

**Comment by BoykoAlex** [comment]
Don't think I'll be able to implement this without `shortDescription` made available to apps list from the server side. The `shortDescription` should be available in the response of `/apps` request. Otherwise, we'd have to send a request to the server for each individual task app (i.e. `apps/taks/timestamp`)

**Comment by sabbyanandan** [comment]
We don't have Task Apps tab anymore.
