### ISSUE TITLE
Add edit link from the Flo-graph to update versions and properties

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#625]
As a user, I'd like to edit the Flo-graph from the list page, so I can update the app versions and its properties.

**Acceptance:**
- Show "edit" link from read-only Flo graph
- Clicking the edit link would redirect to stream deployment page 
- User should be able to update version, deployer, and application properties

Note: This depends on spring-cloud/spring-cloud-dataflow-ui#515 (see [comment](https://github.com/spring-cloud/spring-cloud-dataflow-ui/issues/515#issuecomment-364801670)).

**Comment by LearningCitizen** [comment]
Hi,
I see that this issue is closed so I guess it is resolved.
I am using the 1.5.0 version of Spring Cloud Data Flow, and when I undeploy a stream,then I edit its properties during deployment (shell or with the UI), it just doesn't work. And even in the UI, it is still the old properties that is displayed.
Is it just me or a problem with Spring Cloud Data Flow?

**Comment by sabbyanandan** [comment]
Hi, @LearningCitizen. It'd be better if we don't comment on a closed issue. Please feel free to open a new issue with more details including versions and the steps, so that we can have a look.
