### ISSUE TITLE
Implement modal-window for properties selection from stream deployment

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#647]
This is the same properties modal window used in the Flo canvas; we would like to reuse that.

**Comment by sabbyanandan** [comment]
Depends on #649.

**Comment by BoykoAlex** [comment]
@oodamien I have sketched a possible solution for making properties dialog independent from the graph code. Here is my SCDF UI branch: https://github.com/BoykoAlex/spring-cloud-dataflow-ui/tree/generic-props-dialog. I added you as collaborator.
I think you generally aware how you'd re-use the properties dialog. The problem was to re-use `StreamPropertiesGroupModel` such that graph dependencies are not involved. Now you should be able to use `StreamPropertiesGroupModel` but instead of the graph node you'd need to give it an instance of `PropertiesSource` - it's an interface you'd need to implement. Examples are: `StreamPropertiesSource` and its super class `GraphNodePropertiesSource`. It's best to retun `AppUiProperty` instances... you can ignore `code` (hard-coded for Scriptable-Transform app) and `attr` (used when `applyChanges` is invoked) props for now. We can discuss some details and nuances tomorrow... i'm most interested whether this would take us on the right path.

Instead of the graph cell you'd have:
1. Properties set on an app
2. DetailedAppRegistration object with description, name, id, default value etc.


Let me know how far that is from what you had in mind.
