### ISSUE TITLE
Auto-refresh statuses on the list pages

### ISSUE THREAD

**Issue by dgeswein-dlx** [spring-cloud/spring-cloud-dataflow-ui#749]
In an earlier version of the UI, the deploy status of a stream would automatically update.  Now (using v1.4.0.RELEASE), I have to refresh the page to see the updated status.  I am using the latest version of Chrome.  Thank you!

**Comment by sabbyanandan** [comment]
Hi, @dgeswein-dlx. Thanks for reporting it. 

We have intentionally removed the auto-refresh support since it is possible to overwhelm the backend depending on the number of stream definitions in the list page. We have to query for individual app status by reaching out to the underlying platform runtime (e.g., cf, k8s, etc.) and then reconstitute the related apps into a stream definition to show it in the list. The client-side periodic polling wasn't the elegant approach to this requirement. 

Could you describe why/how you were using the status updates? Were you simply monitoring or for some other reasons? We are going to revisit auto-refresh model, but from the server side, so anything you can share from UX perspective, it'd help to reason through and brainstorm on our side.

**Comment by dgeswein-dlx** [comment]
Ok, I thought it might be a bug since it used to automatically show state change.  I thought it was nice to not have to press the refresh button to watch my deployments go from "deploying" to "deployed" or from "undeploying" to "undeployed".  Maybe there is a way to only poll for status on the streams that are in a transition state (i.e. just the ones  that are "deploying" or "undeploying") - or maybe some other optimization could make this work.

Unrelated, but your comment raised another question.  I thought the pagination was fixed at 10 items in the stream list page - is this page size configurable?  Thank you!

**Comment by sabbyanandan** [comment]
Thanks for the update. We will revisit the auto-refresh requirement in the near future. As for the pagination, with spring-cloud/spring-cloud-dataflow-ui#760, you can select the size of the pagination from the drop-down. It is a predefined static list, though.

![image](https://user-images.githubusercontent.com/1562654/39626054-441f4636-4f55-11e8-98c6-5bc9888bcd7d.png)

**Comment by dgeswein-dlx** [comment]
Awesome!  That will be useful as we have almost 20 streams and being able to deploy/undeploy all at once will save time.

**Comment by sabbyanandan** [comment]
The new Clarity-based UI includes a special configuration section to globally change the page size across all the list pages.
