### ISSUE TITLE
Investigate size increase of the minified SCDF UI

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-ui#843]

**Comment by BoykoAlex** [comment]
This mystery has been revealed.
Just before Flo with JointJS 2.1.2 commit the built minified JS file was 3,580Kb
After the commit it became 3,710Kb
The difference is 130Kb and it came from minified JointJs which grew by 130Kb from 1.0.3 to 2.1.2. I have asked JointJS folks whether it's possible to trim down shapes libraries from the imports since we don't use them anyway and they seem optional.
https://github.com/clientIO/joint/issues/911

**Comment by sabbyanandan** [comment]
We have pushed it and optimized a bit, but unless we can get joint-core as a separate module, we won't be able to push it any further. Let's revisit it once after we get an update from JointJS.
